language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py sdist
# command to run tests
script:
  - echo "testapikey" | python localise/localise.py -c ./config.yml config
